version: '3'

services:
  web:
    build: .
    ports:
     - "5001:3000"
    stdin_open: true
    tty: true
    depends_on: 
      - "mongo"

  
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
